twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_info: '%site_info%'
        lune: '%lune%'
        upload_image_block_directory: '%upload_image_block_directory%'

when@test:
    twig:
        strict_variables: true
