twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        #front_helper: "@App\\Services\\FrontHelper"
        google_tag_manager_id: '%env(GOOGLE_TAG_MANAGER_ID)%'
