vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        block_images:
            uri_prefix: /images/blocks
            upload_destination: '%kernel.project_dir%/public/images/blocks'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true